### ISSUE TITLE
this only work in windows?

### ISSUE THREAD

**Issue by glira** [naqushab/SearchEngineScrapy#1]
i am try install the dependencies and receive this erros in ubuntu:
     Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32->-r requirements.txt (line 2)) (from versions: )
No matching distribution found for pywin32>=223 (from pypiwin32->-r requirements.txt (line 2))
so i am download the complete project to compile 
https://github.com/mhammond/pywin32
and recive this 
$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 95, in <module>
    import _winreg
ImportError: No module named _winreg

so I think that this project only work in windows, please confirm this if I forgot something

**Comment by naqushab** [comment]
@glira Hey,

You don't need to install pypiwin32 for Ubuntu. Just the 2 dependencies will work fine.
Let me know in case of any errors.
The Project is OS independent. :)

**Comment by naqushab** [comment]
I am closing the issue. Feel free to reopen if you got any error.
